// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN83M_WC-vro-ZXtnPzlDLXFQKisiGvjM',
    appId: '1:847976601236:web:828271568c7c0e12d84681',
    messagingSenderId: '847976601236',
    projectId: 'todo-app-62f4e',
    authDomain: 'todo-app-62f4e.firebaseapp.com',
    storageBucket: 'todo-app-62f4e.appspot.com',
    measurementId: 'G-32VHZD59BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZTLnqGrQDIfYoAPW_GMPknu2FucJOL4',
    appId: '1:847976601236:android:b50b4dbd1b65b78cd84681',
    messagingSenderId: '847976601236',
    projectId: 'todo-app-62f4e',
    storageBucket: 'todo-app-62f4e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN83M_WC-vro-ZXtnPzlDLXFQKisiGvjM',
    appId: '1:847976601236:web:ee012b57339f7e67d84681',
    messagingSenderId: '847976601236',
    projectId: 'todo-app-62f4e',
    authDomain: 'todo-app-62f4e.firebaseapp.com',
    storageBucket: 'todo-app-62f4e.appspot.com',
    measurementId: 'G-8CNP8G2Z26',
  );
}
